vein: #有关于连锁挖矿的配置
  has_block_white_list: true #是否开启方块连锁白名单系统
  white_list_blocks: # 如果开启，那么请在这里列出其的id，不要包含minecraft:，且需要为全小写
    - "diamond_ore"
    - "deepslate_diamond_ore"
    - "iron_ore"
    - "deepslate_iron_ore"
    - "coal_ore"
    - "deepslate_coal_ore"
    - "gold_ore"
    - "deepslate_goal_ore"
    - "copper_ore"
    - "deepslate_copper_ore"
    - "emerald_ore"
    - "deepslate_emerald_ore"
    - "redstone_ore"
    - "deepslate_redstone_ore"
    - "lapis_ore"
    - "deepslate_lapis_ore"
    
  max_limit: 64 # 单次连锁最大限制，负数或0=无限制，不建议此值过高，以免服务器卡顿，强烈建议不要过高
anticheat: # 反作弊兼容
  bypass_command: "" # 绕过反作弊指令，%player%=玩家id
  remove_bypass_command: "" # 取消绕过反作弊指令，%player%=玩家id
